//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practica_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        public int ID_Book { get; set; }
        public string BookTitle { get; set; }
        public Nullable<int> ID_Author { get; set; }
    
        public virtual Authors Authors { get; set; }
    }
}
